### PR TITLE
followup from #214

### LINKED ISSUE #482: Use unique commonName when issuing certs with long DNS names
Talked to @KauzClay we'll go ahead an land a fix using the cert look up - though it is uncertain whether it works when renewing certs (which is already broken https://github.com/knative-sandbox/net-certmanager/issues/416).

Thus we'll land this fix in 1.9 and do a subsequent point release that swiches the code over to attempt unique commonNames and fixing renewal in the serving code.

_Originally posted by @dprotaso in https://github.com/knative-sandbox/net-certmanager/issues/214#issuecomment-1401163289_

### PR DESCRIPTION
**Pull request by KauzClay**
# Changes

Fixes #482 

:broom: create unique common names for certs that are too long
* if the non-domain portion (name+namespace data) is long enough, replace it with a base36 version of the kcert UID.
* if that is still too long, then return an error
* update kcert status with details on why the cert isn't ready if CommonName is too long

🗑️ remove code made irrelevant after changes above
* remove broken use of ChildName function
* remove code that looks for matching domain in other certs. Don't need it if we have unique common names
* don't use domain template when creating a common name
* TODO: remove domain template config option

**Release Note**

```release-note

```

### CODE REVIEW

File: pkg/reconciler/certificate/certificate.go [hunk 1]
```diff
@@ -101,26 +101,20 @@ func (c *Reconciler) reconcile(ctx context.Context, knCert *v1alpha1.Certificate
 
 	cmConfig := config.FromContext(ctx).CertManager
 
-	cmCert, err := resources.MakeCertManagerCertificate(cmConfig, knCert)
-	if err != nil {
-		return err
+	cmCert, errCondition := resources.MakeCertManagerCertificate(cmConfig, knCert)
+	if errCondition != nil {
+		certificateCondSet.Manage(&knCert.Status).SetCondition(*errCondition)
+		knCert.Status.MarkNotReady(errCondition.Reason, errCondition.Message)
```
Comment (dprotaso) [inline pkg/reconciler/certificate/certificate.go:107]: Looks like `MarkNotReady` is really setting the status to `Unknown` which is wrong.

What we want is `MarkFailed` to make `Ready=False`

https://github.com/knative/networking/blob/c692e9e6afe17fdd870e19fd04a869585296e315/pkg/apis/networking/v1alpha1/certificate_lifecycle.go#L42

**Review by dprotaso — CHANGES_REQUESTED** [review]

File: pkg/reconciler/certificate/certificate.go (hunk 1 above)
Comment (KauzClay) [reply pkg/reconciler/certificate/certificate.go:107]: Regarding this, and your previous comment about the status. I did it this way because the reconcile just sets a blanket `Ready=Unknown` on any reconcile error: https://github.com/KauzClay/net-certmanager/blob/ck-issue-214-followup/pkg/reconciler/certificate/certificate.go#L88

I was hesitant to change too much of that behavior, but I can

File: pkg/reconciler/certificate/resources/cert_manager_certificate.go [hunk 2]
```diff
@@ -44,22 +55,80 @@ func MakeCertManagerCertificate(cmConfig *config.CertManagerConfig, knCert *v1al
...
-
-			templ = cmConfig.GetCommonNameTemplate()
-
-			if err := templ.Execute(&buf, data); err != nil {
-				return nil, fmt.Errorf("error executing the CommonNameTemplate: %w", err)
+	if len(commonName) > longest {
+		if knCert.Spec.Domain != "" && knCert.Spec.Domain != commonName {
+			//Split out the domain, and create a hash of the remaining part
+			domainSuffix := "." + knCert.Spec.Domain
+			prefix := strings.SplitN(commonName, domainSuffix, 2)[0]
```
[the remark this answers is not in the document]
Comment (KauzClay) [reply pkg/reconciler/certificate/resources/cert_manager_certificate.go:62]: oh, yeah. Idk why I went with SplitN
