### PR TITLE
watch certificate in renewing state

### LINKED ISSUE #416: Renewing the certificate doesn't work as expected and it will call user ksvc for 30 days
We are using cert-manager to manage ksvc certificates and I’ve noticed a weird behaviour.

Be default, cert-manager will create a certificate that will expire in 90 days, then it will try to renew it 30 days before the expiration date.

In this period and when the renew workflow is launched by cert-manager, the certificate is always in `True` state and there is no route in the ingress (we are using Kourier) is configured to forward the traffic `/.well-known/acme-challenge` coming from Lets-encrypt to `cm-acme-http-solver-xxx` pod, so all traffic is instead forwarded to the ksvc pod.

If I understand the [code of net-certmanager](https://github.com/knative-sandbox/net-certmanager/blob/main/pkg/reconciler/certificate/certificate.go#L111) correctly, we are only watching the state of the certificate, and since the certificate is in `True` state, the knative ingress will never be updated so no route will be configured

I'm opening a PR addressing this issue but I'm not `100%` sure that it will work. To reproduce the behaviour we need to wait for 60 days for the renewal process to be lanched (unless there is a workaround for that)

### PR DESCRIPTION
**Pull request by RamyChaabane**
# Changes

🐛  certificate will not be renewed immediately after the renewal process is launched and let's encrypt will call the `user-container` as a consequence  

/kind bug

Fixes #416 

**Release Note**

```release-note
This will configure envoy with the right routes so let's encrpt traffic will no be forwarded to `user-container`
```

### CODE REVIEW

**Comment by carlisia** [comment]
Hey @RamyChaabane, do you think this could possibly be ready to be included in the upcoming `v1.6`?

**Comment by RamyChaabane** [comment]
Hello @carlisia
Yes, it should be ready for the next release
I've tested it locally and it works, need some time to confirm though

File: pkg/reconciler/certificate/certificate.go [hunk 1]
```diff
@@ -116,6 +119,10 @@ func (c *Reconciler) reconcile(ctx context.Context, knCert *v1alpha1.Certificate
 		knCert.Status.MarkNotReady(cmCertReadyCondition.Reason, cmCertReadyCondition.Message)
 		return c.setHTTP01Challenges(knCert, cmCert)
 	case cmCertReadyCondition.Status == cmmeta.ConditionTrue:
+		if cmCertRenewingCondition != nil && cmCertRenewingCondition.Reason == renewReason {
+			knCert.Status.MarkNotReady(cmCertReadyCondition.Reason, cmCertReadyCondition.Message)
+			return c.setHTTP01Challenges(knCert, cmCert)
+		}
```
Comment (dprotaso) [inline pkg/reconciler/certificate/certificate.go:125]: This will transition the `Ready` condition from `True` => `Unknown`. This `Unknown` will propagate up the serving route controller and signal that the cert is not ready and things will downgrade to HTTP.

Since renewing doesn't affect the 'active' certificate  I don't think we should be changing the `Ready` condition.

I wonder if instead we should just introduce a new temporary condition to signal that the certificate is being renewed.

Comment (nak3) [reply pkg/reconciler/certificate/certificate.go:125]: Yeah, it would be better to add a new condition for the renewing.

File: pkg/reconciler/certificate/certificate.go [hunk 2]
```diff
@@ -107,6 +108,8 @@ func (c *Reconciler) reconcile(ctx context.Context, knCert *v1alpha1.Certificate
 	// Propagate cert-manager Certificate status to Knative Certificate.
 	cmCertReadyCondition := resources.GetReadyCondition(cmCert)
 	logger.Infof("cm cert condition %v.", cmCertReadyCondition)
+	cmCertRenewingCondition := resources.GetRenewingCondition(cmCert)
```
Comment (nak3) [inline pkg/reconciler/certificate/certificate.go:111]: I wonder that it would be better to kick the reconciliation by if `knCert.Status.NotAfter` was changed? (currently L#107 just copied but I think we should check the diff.).

The `GetRenewingCondition` also works but it can surely reconcile the knCert after renewed, I think.

File: pkg/reconciler/certificate/certificate.go [hunk 3]
```diff
@@ -116,6 +121,17 @@ func (c *Reconciler) reconcile(ctx context.Context, knCert *v1alpha1.Certificate
 		knCert.Status.MarkNotReady(cmCertReadyCondition.Reason, cmCertReadyCondition.Message)
 		return c.setHTTP01Challenges(knCert, cmCert)
 	case cmCertReadyCondition.Status == cmmeta.ConditionTrue:
+		if cmCertRenewingCondition != nil && cmCertRenewingCondition.Reason == renewingEvent {
```
Comment (nak3) [inline pkg/reconciler/certificate/certificate.go:124]: So the `renewingEvent` (`Renewing`) is from https://github.com/cert-manager/cert-manager/blob/master/internal/controller/certificates/policies/constants.go#L41-L43 but we cannot import the internal lib so we defined it in Line#59?
And if cert-manager changed the `Renewing` word, our code will break and nobody notice it, won't it.

So, I still think that we should trigger the reconile loop by `NotAfter` instead of the `Renewing` as https://github.com/knative-sandbox/net-certmanager/pull/417/files#r901272781 commented.

Comment (RamyChaabane) [reply pkg/reconciler/certificate/certificate.go:124]: @nak3 
> So the renewingEvent (Renewing) is from https://github.com/cert-manager/cert-manager/blob/master/internal/controller/certificates/policies/constants.go#L41-L43 but we cannot import the internal lib so we defined it in Line#59?

yes

> And if cert-manager changed the Renewing word, our code will break and nobody notice it, won't it.

I don't think the code will break, but definitely will not notice it, I think it will have the current behaviour

> So, I still think that we should trigger the reconile loop by NotAfter instead of the Renewing as https://github.com/knative-sandbox/net-certmanager/pull/417/files#r901272781 commented.

`NotAfter` field indicates when the certificate will expire, not when it should be renewing. I'm not sure if I fully understand your comment, but you would like something like this, right?
```
knCert.Status.NotAfter = cmCert.Status.RenewalTime
```
and check the diff between `knCert.Status.NotAfter` and the current time

Comment (nak3) [reply pkg/reconciler/certificate/certificate.go:124]: > NotAfter field indicates when the certificate will expire, not when it should be renewing.

I assumed that cert-manager updates the `NotAfter` field when it renewed the certificate. If the assumption is true, we can add the trigger to update the status like this?

```go
	// Line around 106
	renewed := false
	if knCert.Status.NotAfter != cmCert.Status.NotAfter {
		renwed = true
	}
	knCert.Status.NotAfter = cmCert.Status.NotAfter

	//  ... snip ... //

	switch {
	case cmCertReadyCondition.Status == cmmeta.ConditionTrue:
		if renewed {
			// set renew condition
			renewCondition := apis.Condition{
				Type:   renewingEvent,
				Status: corev1.ConditionTrue,
			}
			certificateCondSet.Manage(&knCert.Status).SetCondition(renewCondition)
			return c.setHTTP01Challenges(knCert, cmCert)
		}
		// ...
	}
```

Comment (RamyChaabane) [reply pkg/reconciler/certificate/certificate.go:124]: > I assumed that cert-manager updates the NotAfter field when it renewed the certificate

Yes, but the cert-manager certificate will never be renewed if we do not tell the ingress to setup HTTP challenges routes. Therefore, cert-manager `NotAfter` field won't change until the certificate expires, meaning `knCert.Status.NotAfter != cmCert.Status.NotAfter` will never happen before expiration

Maybe something like that will work (I'm testing it)
```
        // Propagate cert-manager Certificate status to Knative Certificate.
	renewalTime := cmCert.Status.RenewalTime
	now := time.Now()
	if now.Before(renewalTime.Time) {
		knCert.Status.NotAfter = renewalTime
	} else {
		knCert.Status.NotAfter = nil
	}
```

**Comment by RamyChaabane** [comment]
Hello @nak3 
please let me know what you think. The last suggestion seems to be working
Thanks !

File: pkg/reconciler/certificate/certificate.go [hunk 4]
```diff
@@ -104,6 +108,11 @@ func (c *Reconciler) reconcile(ctx context.Context, knCert *v1alpha1.Certificate
 	}
 
 	knCert.Status.NotAfter = cmCert.Status.NotAfter
+	renewed := false
+	if cmCert.Status.RenewalTime != nil && time.Now().After(cmCert.Status.RenewalTime.Time) {
```
Comment (nak3) [inline pkg/reconciler/certificate/certificate.go:112]: Could you add a comment line for this with your issue link https://github.com/knative-sandbox/net-certmanager/issues/416 ?
I think this issue is difficult to notice and understand.

**Review by nak3 — COMMENTED** [review]
Thank you so much! 
I added two minor comments but LGTM.

**Comment by nak3** [comment]
/hold
/lgtm
/approve

`/hold` for one day if there is any other review comments.
